### ISSUE TITLE
Issue with re-exporting types and interfaces

### ISSUE THREAD

**Issue by wizluo** [Caesar2011/valideno#3]
Hey @Caesar2011,

I've tried to use valideno in my project but unfortunately with no luck. 
I'm getting errors: 

```
ERROR TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Args,
  ~~~~
    at https://deno.land/x/valideno@v1.0.0/mod.ts:2:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Validator,
  ~~~~~~~~~
    at https://deno.land/x/valideno@v1.0.0/mod.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ValidationError,
  ~~~~~~~~~~~~~~~
    at https://deno.land/x/valideno@v1.0.0/mod.ts:4:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Validatable,
  ~~~~~~~~~~~
    at https://deno.land/x/valideno@v1.0.0/mod.ts:6:3
```

Isn't those four exports should be exported in _mod.ts_ file like below, with **_type_** instead of just an **_export_**?

```
export type {
    Args,
    Validatable,
    ValidationError,
    Validator,
} from './Validator.ts';
```

**EDIT: I tested it myself and this change seems to fix the problem. PR for this change is here: #4**

**Comment by wizluo** [comment]
@Caesar2011, if PR is merged, could you make also a new version to be able to use it from deno.land?

**Comment by dareksob** [comment]
Still a problem, please release new fixed version.
